services:
  laravel.test:
    ports:
      - '5173:5173'
    volumes:
      - type: bind
        source: '/home/marke/code/sail/infrastructure/certs'
        target: '/sail-manager/certs'
        read_only: true
  web:
    networks:
      - default
      - sail-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=sail-proxy
      - traefik.http.routers.finance.rule=Host(`finance.test`)
      - traefik.http.routers.finance.entrypoints=websecure
      - traefik.http.routers.finance.tls=true
      - traefik.http.services.finance.loadbalancer.server.port=80

networks:
  sail-proxy:
    external: true