#!/usr/bin/env bash
DEPLOY_APP=finance
DEPLOY_DEFAULT_URL=''
DEPLOY_DB_CONNECTIONS=ledger,catalog
DEPLOY_TABLE_PREFIX=''
DEPLOY_EXCLUDE_PREFIX=''
DEPLOY_EXPECTED_DATABASE=''
DEPLOY_CATALOG_MIGRATIONS=true
DEPLOY_SESSION_CHECK=false
DEPLOY_TEST_CONNECTION=ledger
